# Generated by Django 4.0.1 on 2022-08-20 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='age',
            field=models.CharField(default='0', max_length=4),
        ),
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='book',
            name='format',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='book',
            name='place',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=600)),
                ('date', models.DateTimeField(verbose_name='Date published')),
                ('connect_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
