# Generated by Django 4.0.1 on 2022-08-21 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_age_book_content_book_format_book_pages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='connect_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='books.book'),
        ),
    ]
