# Generated by Django 4.0.1 on 2022-08-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('NEW', 'New'), ('BESTSELLER', 'Bestseller'), ('HISTORY', 'History'), ('SCIENCE', 'Science')], default='NEW', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.CharField(default='', max_length=50),
        ),
    ]
