# Generated by Django 4.0.1 on 2022-08-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_expert_alter_book_content_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.CharField(default='', max_length=15),
        ),
    ]
