# Generated by Django 4.0.1 on 2022-08-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('NEW', 'New'), ('BESTSELLER', 'Bestseller'), ('HISTORY', 'History'), ('SCIENCE', 'Science'), ('AUDIO', 'Audio')], default='NEW', max_length=100),
        ),
    ]
